#!/usr/bin/env python3
"""
generate_path_sequence.py --path IDLE,READ,WRITE,DONE [--classname MyPathSeq] [--base svgraph_sequence] [--end __END__] [--outdir .]
"""

import argparse
import os

def main():
    parser = argparse.ArgumentParser(description='Generate a UVM sequence class with a fixed path constraint.')
    parser.add_argument('--path', required=True, help='Comma-separated list of states, e.g. IDLE,READ,WRITE,DONE') //ну вообще это последовательность состояний которую мы хотим 
    parser.add_argument('--classname', default='fixed_path_sequence', help='Name of the generated class (default: fixed_path_sequence)')
    parser.add_argument('--base', default='svgraph_sequence', help='Base sequence class name (default: svgraph_sequence)')
    parser.add_argument('--end', default='__END__', help='Name of the final pseudo-state (default: __END__)') //
    parser.add_argument('--outdir', default='.', help='Output directory (default: current directory)')
    args = parser.parse_args()

    states = [s.strip() for s in args.path.split(',') if s.strip()]
    if len(states) < 1:
        print("Error: path must contain at least one state")
        return 1

    outfile = os.path.join(args.outdir, f"{args.classname}.sv")
    with open(outfile, 'w') as f:
        f.write(f"// Automatically generated by generate_path_sequence.py\n")
        f.write(f"// Path: {args.path}\n\n") 
        
        f.write(f"`include "uvm_macros.svh"\n")
        f.write(f"import uvm_pkg::*;"\n")
        f.write(f"import my_fsm_pkg::*;\n\n")

        f.write(f"class {args.classname} extends {args.base};\n") // args.base must be ,my_fsm_sequence,
        f.write(f"  `uvm_object_utils({args.classname})\n\n")

        f.write(f"  function new(string name = \"{args.classname}\");\n")
        f.write(f"    super.new(name);\n")
        f.write(f"  endfunction\n\n")

        f.write(f"  constraint path_weights {{\n")

        for i in range(len(states)-1):
            src = states[i]
            dst = states[i+1]
            f.write(f"    weight[{src}][{dst}] == 100;\n")

        if states:
            f.write(f"    weight[{states[-1]}][{args.end}] == 100;\n")

        f.write(f"    foreach (weight[src, dst]) {{\n")
        f.write(f"      if (!(")
        conditions = []
        for i in range(len(states)-1):
            conditions.append(f"(src == {states[i]} && dst == {states[i+1]})")
        if states:
            conditions.append(f"(src == {states[-1]} && dst == {args.end})")
        f.write(" || ".join(conditions))
        f.write(f")) weight[src][dst] == 0;\n")
        f.write(f"    }}\n")
        f.write(f"  }}\n\n")

        f.write(f"  constraint no_dec {{\n")
        f.write(f"    weight_default_decrement == 0;\n")
        f.write(f"  }}\n\n")

        f.write(f"endclass\n")

    print(f"Generated {outfile}")

if __name__ == "__main__":
    main()
