// Automatically generated by generate_path_sequence.py (modified manually)
// Path: IDLE,READ,WRITE,DONE


`include "uvm_macros.svh"
import uvm_pkg::*;
import my_fsm_pkg::*;

class my_path_seq extends my_fsm_sequence;
  `uvm_object_utils(my_path_seq)

  function new(string name = "my_path_seq");
    super.new(name);
  endfunction

  constraint path_weights {
    weight[__START__][IDLE] == 100;   
    weight[IDLE][READ] == 100;
    weight[READ][WRITE] == 100;
    weight[WRITE][DONE] == 100;
    foreach (weight[src, dst]) {
      if (!((src == __START__ && dst == IDLE) || 
            (src == IDLE && dst == READ) || 
            (src == READ && dst == WRITE) || 
            (src == WRITE && dst == DONE))) 
        weight[src][dst] == 0; // для всех остальных вес 0/
    }
  }

  constraint no_dec {
    weight_default_decrement == 0; // запрет уменьшения веса
  }

  virtual task IDLE_body();
    $display(">>> In IDLE state");
  endtask

  virtual task READ_body();
    $display(">>> In READ state");
  endtask

  virtual task WRITE_body();
    $display(">>> In WRITE state");
  endtask

  virtual task DONE_body();
    $display(">>> In DONE state - exiting");
    exit(); // автозавершение
  endtask

endclass
